language: php

sudo: false

branches:
  only:
    - master

php:
  - 7.0
  - hhvm

env:
  - DB=mysql

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - python3
      - python-pip
      - clang-format-3.7

# Disables default git submodules.
# This is done to only download the modules required for testing.
git:
  submodules: false

before_install:
  - |
      ! [ $TRAVIS_PHP_VERSION == "hhvm" ] || git submodule update --init \
          frontend/server/libs/third_party/smarty \
          frontend/server/libs/third_party/phpmailer \
          frontend/server/libs/third_party/log4php \
          frontend/server/libs/third_party/adodb \
          frontend/server/libs/third_party/facebook-php-graph-sdk \
          frontend/server/libs/third_party/google-api-php-client
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || git submodule update --init \
          stuff/hook_tools
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || pip install --user six
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || pip install --user \
         https://github.com/google/closure-linter/zipball/master
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || nvm install 6.9.1
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || npm install -g yarn

cache:
  directories:
  - $HOME/.yarn-cache

before_script:
  - |
      ! [ $TRAVIS_PHP_VERSION == "hhvm" ] || \
          mysql -e 'CREATE DATABASE IF NOT EXISTS `omegaup-test`'
  - |
      ! [ $TRAVIS_PHP_VERSION == "hhvm" ] || \
          mysql -uroot -e "GRANT ALL ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;"
  - |
      ! [ $TRAVIS_PHP_VERSION == "hhvm" ] || \
          python3 stuff/db-migrate.py --username=travis --password= \
          migrate --databases=omegaup-test
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || \
          (pear install pear/PHP_CodeSniffer-2.6.2 && phpenv rehash)

script:
  - |
      ! [ $TRAVIS_PHP_VERSION == "hhvm" ] || \
          phpunit --bootstrap frontend/tests/bootstrap.php --configuration \
          frontend/tests/phpunit.xml frontend/tests/controllers
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || (yarn install && yarn build && yarn test)
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || \
          python3 stuff/i18n.py --validate < /dev/null
  - |
      ! [ $TRAVIS_PHP_VERSION != "hhvm" ] || \
          python3 stuff/hook_tools/lint.py validate --all < /dev/null

notifications:
  slack:
    secure: Dw6yE/lCYGuAvZDthzUAxqYMzn6CxPvNaCt1RheZPs9Na7gq/LWbfPz1g7vigwvNzBDd8+NFHAo4HEZ5ajWyoXeL2b83P7+sn6sZZcpO3ZG2kjNqkroW84Aum5l3KHqi8aIvAfNXZyQm5WUABKktEza7vGUeWZs1PAu8OJuLdIU=
