language: php

dist: trusty

group: edge

sudo: false

branches:
  only:
    - master

php:
  - 7.0.7
  - 7.1

env:
  - DB=mysql

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - python3
      - python-pip
      - clang-format-3.7

# Disables default git submodules.
# This is done to only download the modules required for testing.
git:
  submodules: false

before_install:
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" != 7.1* ]] || git submodule update --init \
         frontend/server/libs/third_party/smarty \
         frontend/server/libs/third_party/phpmailer \
         frontend/server/libs/third_party/log4php \
         frontend/server/libs/third_party/adodb \
         frontend/server/libs/third_party/facebook-php-graph-sdk \
         frontend/server/libs/third_party/google-api-php-client
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || git submodule update --init \
         stuff/hook_tools
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || pip install --user six
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || pip install --user \
         https://github.com/google/closure-linter/zipball/master
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || nvm install 6.9.1
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || npm install -g yarn

cache:
  directories:
  - $HOME/.yarn-cache

before_script:
  # Workaround for Travis' flaky MySQL connection.
  - for _ in `seq 30`; do mysql -e ';' && break || sleep 1 ; done
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" != 7.1* ]] || \
         mysql -e 'CREATE DATABASE IF NOT EXISTS `omegaup-test`'
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" != 7.1* ]] || \
         mysql -uroot -e "GRANT ALL ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;"
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" != 7.1* ]] || \
         python3 stuff/db-migrate.py --username=travis --password= \
         migrate --databases=omegaup-test
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" != 7.1* ]] || \
         mysql -uroot -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');"
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || \
         (pear install pear/PHP_CodeSniffer-2.9.1 && phpenv rehash && \
          echo "include_path='.:/home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/pear/:/home/travis/.phpenv/versions/$(phpenv version-name)/share/pear'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini)

script:
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" != 7.1* ]] || \
         phpunit --bootstrap frontend/tests/bootstrap.php --configuration \
         frontend/tests/phpunit.xml frontend/tests/controllers
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || (yarn install && yarn build && yarn test)
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || \
         python3 stuff/i18n.py --validate < /dev/null
  - |
      ! [[ "${TRAVIS_PHP_VERSION}" == 7.1* ]] || \
         python3 stuff/hook_tools/lint.py -j4 validate --all < /dev/null

notifications:
  slack:
    secure: Dw6yE/lCYGuAvZDthzUAxqYMzn6CxPvNaCt1RheZPs9Na7gq/LWbfPz1g7vigwvNzBDd8+NFHAo4HEZ5ajWyoXeL2b83P7+sn6sZZcpO3ZG2kjNqkroW84Aum5l3KHqi8aIvAfNXZyQm5WUABKktEza7vGUeWZs1PAu8OJuLdIU=
