language: php

dist: trusty

group: edge

sudo: false

branches:
  only:
    - master

php:
  - 7.0.7

env:
  - TEST_SUITE=phpunit
  - TEST_SUITE=lint
  - TEST_SUITE=selenium

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - nginx
      - realpath
      - python3
      - python-pip
      - python3-pip
      - clang-format-3.7
  sauce_connect:
    username: lhchavez
    access_key:
      secure: PjNJHqneJ7qPBxbZEmgBemJT6tFE+sHKmVGQ2GwzaXSHT+3cthzTjMGe/k/fi+XiiuMTfHXs09uF6bEzJAMPW6PeCjkOYR+9H5btMmEEQJvdJBafNTbL26xSr4bBNLYBlryudDCx4hKDXOGoIPCJ+mhKHTtwApbfdx5ec8r1kD4=

cache:
  directories:
    - $HOME/.yarn-cache

# Disables default git submodules.
# This is done to only download the modules required for testing.
git:
  submodules: false

before_install: stuff/travis/run.sh "${TEST_SUITE}" before_install

install: stuff/travis/run.sh "${TEST_SUITE}" install

before_script: stuff/travis/run.sh "${TEST_SUITE}" before_script

script: stuff/travis/run.sh "${TEST_SUITE}" script

notifications:
  slack:
    secure: Dw6yE/lCYGuAvZDthzUAxqYMzn6CxPvNaCt1RheZPs9Na7gq/LWbfPz1g7vigwvNzBDd8+NFHAo4HEZ5ajWyoXeL2b83P7+sn6sZZcpO3ZG2kjNqkroW84Aum5l3KHqi8aIvAfNXZyQm5WUABKktEza7vGUeWZs1PAu8OJuLdIU=
